label bdf4:
    "I’ve decided to go for the final push, I can practically feel danger crawling on my spine."
    mc "You know, you sure seem awfully nervous when we have the recall technology on our side."
    mc "I’ll leave as soon as I’m done with the mission."
    py "That’s true but…"
    mc "There’s a but?"
    py "You should only rely on recall sparingly…"
    mc "Why?"
    "Before I can get my answer, the murderous intent has caught my attention and prompted me to turn."
    py "There it is! That’s the True Sting!"
    mc "This looks way more dangerous than anything we’ve encountered…"
    py "Too late for regrets now! Prepare to commit!"

    Commit True String

    mc "It’s way too strong! Looks like it got bored of us and left, though..."
    py "Enough about that! We’ve got its DNA let’s hurry up and leave!"
    py "Let’s recall and submit the research!"
    mc “I’m already trying to…. but…"
    "Recall has been banned."
    "The surroundings suddenly start to turn red."
    mc "It’s disabled…"
    py "..."
    "Even though, we went through all that…"
    mc "There must be another way, but first we have to get out of here!"
    "I try to backtrack."
    "But..."
    mc "It’s blocked!"
    py "..."
    mc "I can’t call Hiyajou either!"
    py "Yuuki."
    mc "Huh?"
    py "I think we’re out of luck."
    mc "Out of luck?"
    "Pychan stares straight into my soul."
    py "I told you, didn’t I? Nobody can exit the danger zone."
    mc "!"
    py "If I have to guess, Project Prologue already took control of the firewall."
    py "But regardless of the method, we can’t do anything anymore."
    mc "..."
    py "But don’t worry. You still have me."
    py "AI cannot detoriate away, so I’ll stay with you."
    py "Forever."
    "Looks like I really messed up this time."
    “I try many times but recall keeps on giving me the silent treatment."
    "Looks like I’m stuck here."
    "There’s no way out."
    "Not even the sound of anyone."
    "Except for Pychan."
    "This mission… is a failure."
    "Chapter 1: Ending 2"

    
