label df4:
    #mc = yuki py = pychan maid = yuri
    "And here we are. Right in front of the Hive."
    "But this seems way too peaceful... Where are all the guards?"
    py "There's no doubt about it, I think this is the Hive."
    mc "You think? They might as well just give me a DNA extractor..."
    py "Well, keeping you entertained is one of my instructions."
    mc "So? Are we going in or not?"
    maid "Do you wish to have an audience with the queen?"
    "I was about to bust through the gate but someone was already in front of me."
    maid "Good day, I am Yuri. The head maid of lady Reine. Do you have any business with her? I can lead the way."
    "So Reine is really here."
    "And is that a basket of fresh lemons back there..?"
    py "What is a maid doing in a mafia gang?"
    "I guess the mafias are keeping up with the trend."
    mc "I want to talk to Reine so can you lead the way?"
    "Yuri wears a smile and starts evaluating me from afar."
    maid "I'm glad you came to see lady Reine too."
    py "Too? Did she mean Lemon?"
    maid "I'm glad that we're having some guests."
    maid "But..."
    mc "..."
    maid "It pains me to say this. But I cannot let you pass."
    py "Huh..?"
    maid "The queen's wish is my demand. That goes for stopping the LAB:MEM as well."
    maid "I won't let you guys hurt her again!"
    py "Looks like the only way out is to commit..."
    mc "No helping it. Don't think I'll go easy just because you're a girl."

    ###Commit!###

    maid "You're strong..."
    maid "You're actually just here to extract the DNA from True String, aren't you?"
    mc "How did you know?"
    maid "If not for research, why would LAB:MEM come here?"
    "Are we really that boring?"
    maid "Truth be told, I already knew you guys aren't up to no good."
    maid "But I've still got work to do."
    mc "Let me guess, Project Prologue again."
    maid "..."
    "Yuri still wears her smile but it can't really hide anything."
    "This facade of a smile is something she's trained to do."
    maid "After the boss passed away. Lady Reine had to do the dirty work after him."
    maid "She's always berated at school, and at some point, she stopped attending entirely."
    maid "I've been with her since forever. The hierarchy of Hivemind Boss and the maid goes way back."
    maid "Honestly, I don't agree with how things work in Hivemind either. It disgusts me."
    maid "Lady Reine is kind, she isn't like them. She entered the simulated universe to prove that."
    maid "But as soon as she set foot here, everyone already resent her and even made accusations."
    mc "Accusations?"
    maid "The queen does not have what you're looking for."
    mc "You mean... the True Sting?"
    maid "Like I said, we don't have the True String at all. We don't even know where it is now."
    py "Aside from here, we would only have the danger zone left. And can we even trust her?"
    py "Like the name implied, that zone is of high danger-level. Those who entered never came back. I wouldn't advise to do it."
    maid "Whether you want to believe it or not is your choice. If you don't then come this way."
    ###choice###
        "Enter the Hive":
            maid "I see. Then follow me."
            maid "There's actually something else I want to say. But I'll leave it to the queen."
            maid "I'm sure she will speak her mind because I know what kind of person she is."
            # call df0_fight
        "Take a detour":
            py "Wait, are you sure about this? Did you not hear what I just said?"
            mc "With you here, what is there to afraid? We've got a mission to complete."
            mc "And we can just recall when things get bad, can't we?"
            py "But still!"
            mc "Then, I'll take a detour."
            maid "I see. Then, please excuse me."
            "Yuri left, contented."
            # call df0_fight
