label df5:
    "To find out the truth for myself, I entered the Hive with Pychan and Yuri."
    maid "This is as far as I can help you, I'll take my leave."
    "Yuri walks off into the distant hallway, leaving only me and Pychan."
    py "Looks like the mission is nearing its end."
    mc "What if she really doesn't have the True Sting?"
    py "There's no doubt about it. If the True Sting is free in the danger zone, even the food chain there will be ruined."
    py "Now let's finish this."
    ##Entering the Throne Room###
    "After entering the throne room, there were already two people. One down, and one thriving."
    py "Isn't that Lemon? Why is she down on the floor?"
    mc "So, you really were an enemy!"
    reine "Could you perhaps be her acquaintance, LAB:MEM?"
    reine "My name is Reine des Abeilles, the rightful heir of Hivemind."
    reine "If you've made it this far, it means Yuri let you pass, didn't she?"
    mc "I'll have you know, we bulldozed our way through her."
    py "Don't make us sound like the villains here!"
    reine "How you made it here doesn't matter, this is as far as you'll go."
    reine "I know you LAB:MEMs never give up without a fight, so please excuse me for destroying you here and now."
    reine "I need those research you're holding after all."
    py "She's getting full of herself just because she's the boss, let her have it!"

    ###Commit!###

    reine "How... I was doing exactly as instructed..."
    py "Why didn't she bring out the True Sting?"
    "That's because she doesn't even have it..."
    "But instructions? For what?"
    reine "I just want to cleanse the name of my blood..."
    reine "Those guys said that the world will be saved if we can stop the LAB:MEM."
    reine "Even if I didn't believe it. I don't really have much of a choice."
    lemon "So you just do as they say? That's it?"
    mc "LEMON!?"
    lemon "Oh, it's you again. How long have I been out."
    reine "Approximately 4 hours."
    lemon "Why, that's nothing!"
    mc "What's going on here, she didn't knock you out?"
    lemon "Oh, that? I just came to talk business with lady Reine here, so she brought me these fresh lemonade."
    lemon "I just can't get enough of it and caught a brain freeze, sorry about that."
    mc "..."
    py "..."
    reine "Yuri is already on her way to harvest more lemons. Don't worry, there will be enough for everyone."
    "So that's what the basket was all about..."
    lemon "So what did you come here for?"
    mc "I came for the True Sting but it doesn't seem to be here."
    reine "The rumors again, I see. I'm used to it."
    lemon "So that's it... Let's get to the point then."
    lemon "I'm here to collect the debt from the Hivemind."
    lemon "But when I'm here, the lemonade was worth way more!"
    mc "What a sour reason..."
    lemon "So I think I was going to change my mind but I passed out first."
    reine "You mean you will lift the debt!?"
    py "She's more generous than I thought."
    lemon "Well, you're half right. But there's a condition."
    reine "A condition?"
    lemon "First, you have to transform the Hivemind into a lemonade factory."
    "This is going way too overboard..."
    lemon "Our company will back it up so it's sure to be famous worldwide, or universewide..."
    lemon "The mafia gang will be as good as disbanded and your name is cleansed, isn't this just perfect?"
    reine "It certainly seems tempting."
    "She likes lemonade that much? I feel like I used to know someone like that."
    lemon "Now for the last condition, give us your assistance and help us put an end to Project Prologue instead."
    lemon "I know that you were forced to comply, but don't worry, we're your allies."
    mc "Well, there's that. I was just sent by Hiyajou, no hard feelings."
    py "Stop with the villain talk already!"
    mc "But the desire to turn over a new leaf. I can dig that."
    mc "Project Prologue is indiscriminately striving for their goal. Who knows how many people they've hurt."
    mc "I'm sure someone as kind and strong as you will be of great help."
    py "Being an mc all of a sudden, huh?"
    reine "..."
    reine "If that's what you think then I'm glad to help."
    reine "Project Prologue reminds me of the old Hivemind, I'll help you stop them from hurting more people."
    reine "Listen, their real goal is to-"
    "************************************************"
    "But suddenly Reine disappeared into thin air, and the surroundings turned all red."
    lemon "Did she just get force-recalled?!"
    mc "Force-recall? What is that?"
    "Yuri storms in."
    yuri "Reine! Lady Reine!"
    mc "Let's recall and notify Hiyajou!"
    lemon "Yeah, and quick!"
    "We all try to initiate the recall process."
    "But to no avail..."
    lemon "It's not working..."
    mc "Doesn't look like I can connect to Hiyajou either, are we stuck here?"
    yuri "Lady Reine!"
    mc "Pychan! Status report?"
    py "..."
    py "This is bad."
    mc "On a scale of 10?"
    py "Could be an 11. Looks like Project Prologue already gained full control of the firewall."
    mc "Can't you do anything about it with your mighty AI technology?"
    py "Well, do you think ChatGPT would be able to do anything about it?"
    mc "ChatGP- What are you even talking about?"
    lemon "I don't think Project Prologue can completely take authority of the firewall."
    lemon "We have to figure out what they did and stop them fast."
    "Why did they do it right after Reine was about to say something important..."
    "Could it be our fault that lady Reine disappeared?"
    "Were their eyes on us this whole time?"
    "What is happening to the simulated universe?"
    "My mind is in a tempest but I cannot stop here."
    "Just wait for me, I'll save you, Reine. ...But for now, I'll have to 'save' the game first, please excuse me."
    "Chapter 1: Ending 1"








